Repository kowainik/hintman, pull requests merged in 2018-11, with the labels that each got.

#18 [#13] Add hlint checks in travis ci
  .travis.yml
Labels: CI

#7 [#1] basic api with generic-servant;
  app/Main.hs
  hintman.cabal
  src/Hintman/App.hs
  src/Hintman/Server.hs
  stack.yaml
Labels: api

#15 [#11] Use optparse-applicative for parsing configuration
  app/Main.hs
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App.hs
  src/Hintman/Cli.hs
Labels: cli

#16 [#3] Suggest function
  hintman.cabal
  src/Hintman/Suggestion/Core.hs
  src/Hintman/Suggestion/TrailingSpaces.hs
Labels: enhancement

#25 [#23] Implement simple auth layer
  hintman.cabal
  src/Hintman.hs
  src/Hintman/Server.hs
  src/Hintman/Server/Auth.hs
Labels: api

#26 [#9] Config data type
  hintman.cabal
  src/Hintman/Config.hs
  stack.yaml
Labels: configuration

#20 [#2] Implement JWT payload signing
  hintman.cabal
  src/Hintman/GitHub/Auth.hs
  src/Prelude.hs
Labels: enhancement

#19 [#4] Add property tests for trailing spaces
  hintman.cabal
  src/Hintman/Suggestion/Core.hs
  test/Spec.hs
  test/Test/Suggestion.hs
Labels: tests
