Repository kowainik/hintman, pull requests merged in 2019-08, with the labels that each got.

#62 [#50] Integrate GitHub webhooks
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App/Env.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Server.hs
  src/Hintman/Server/Auth.hs
  src/Hintman/Webhook.hs
  stack.yaml
Labels: github api, library

#63 [#51] Print parsed diff of incoming PRs
  hintman.cabal
  src/Hintman/Core/PR.hs
  src/Hintman/Diff.hs
  src/Hintman/GitHub/Auth.hs
  src/Hintman/Webhook.hs
  src/Prelude.hs
  stack.yaml
Labels: enhancement, github api

#64 [#60] Upgrade to latest libraries
  hintman.cabal
  stack.yaml
Labels: library

#65 [#54] Learn how to submit PR reviews
  hintman.cabal
  src/Hintman/Comment.hs
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Core/Review.hs
  src/Hintman/Diff.hs
  src/Prelude.hs
Labels: github api

#67 [#52] Run HLint over the content of files in PR
  hintman.cabal
  src/Hintman/Core/PrInfo.hs
  src/Hintman/HLint.hs
  stack.yaml
  test/Spec.hs
  test/Test/Config.hs
  test/Test/Data.hs
  test/Test/HLint.hs
  test/Test/Suggestion.hs
Labels: enhancement, hint

#68 [#66] Figure out authentication for GitHub App and use proper token for submitting comments
  .gitignore
  README.md
  cabal.project
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App/Env.hs
  src/Hintman/Comment.hs
  src/Hintman/Core/Key.hs
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Core/Token.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/HLint.hs
  src/Hintman/Installation.hs
  src/Hintman/Webhook.hs
  src/Prelude.hs
  stack.yaml
Labels: enhancement, github api, library, refactoring

#74 [#39] Introduce logging with `co-log`
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App/Env.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Comment.hs
  src/Hintman/Core/Token.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/HLint.hs
  src/Hintman/Installation.hs
  src/Hintman/Webhook.hs
  src/Prelude.hs
  test/Test/HLint.hs
Labels: enhancement

#75 [#71] Implement proper caching of InstallationId
  cabal.project
  hintman.cabal
  src/Hintman/App.hs
  src/Hintman/App/Env.hs
  src/Hintman/App/Error.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Core/Token.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/Installation.hs
  src/Hintman/Webhook.hs
  stack.yaml
Labels: github api

#78 [#53] Implement pure function to generate text of comment
  src/Hintman/HLint.hs
  test/Test/HLint.hs
Labels: HLint, enhancement, hint

#83 [#76] Implement `acquireInstallationToken` function
  hintman.cabal
  src/Hintman/App/Env.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Effect/TokenStorage.hs
Labels: docs, enhancement, help wanted
