Repository kowainik/hintman, pull requests merged in 2019-10, with the labels that each got.

#92 [#79] Make sure that suggestion doesn't remove any parts of the line
  hintman.cabal
  src/Hintman/Core/Review.hs
  src/Hintman/HLint.hs
  test/Test/HLint.hs
Labels: HLint

#91 [#72] Configure hintman for Heroku deployment
  Procfile
  src/Hintman.hs
  src/Hintman/Cli.hs
  stack.yaml
Labels: CI

#95 [#93] Get commentPosition from line in source
  src/Hintman/HLint.hs
  test/Test/HLint.hs
Labels: HLint, diff

#96 Try to fix heroku
  src/Hintman.hs
Labels: CI

#97 [#90]: Bump github-webhook to 0.11.0
  hintman.cabal
  stack.yaml
Labels: library

#100 [#94] Implement tests for some standard HLint rules
  test/Test/HLint.hs
Labels: tests

#99 [#81] Run HLint with "--ignore=Parse error" flag
  test/Test/Data.hs
  test/Test/HLint.hs
Labels: tests

#103 [#56] Submit all hints when a PR is open
  src/Hintman/App/Monad.hs
  src/Hintman/Comment.hs
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Diff.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/HLint.hs
  src/Hintman/Webhook.hs
  src/Prelude.hs
  test/Test/Data.hs
  test/Test/HLint.hs
Labels: github api

#107 [#101] Write README
  README.md
Labels: docs

#108 Refactor Hints
  hintman.cabal
  src/Hintman/Config.hs
  src/Hintman/Core/Hint.hs
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Core/Review.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/HLint.hs
  src/Hintman/Hint/TrailingNewline.hs
  src/Hintman/Hint/TrailingSpaces.hs
  src/Hintman/Suggestion/Aggregation.hs
  src/Hintman/Suggestion/Core.hs
  src/Hintman/Webhook.hs
  test/Test/Config.hs
  test/Test/HLint.hs
  test/Test/Suggestion.hs
Labels: enhancement, refactoring

#109 Refactor hints and tests
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App/Env.hs
  src/Hintman/Config.hs
  src/Hintman/Core/Hint.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/TrailingNewline.hs
  test/Spec.hs
  test/Test/Config.hs
  test/Test/Suggestion.hs
Labels: refactoring

#112 [#104] Include trailing spaces comments into the review
  hintman.cabal
  src/Hintman/Core/Hint.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/HLint.hs
  src/Hintman/Hint/Position.hs
  src/Hintman/Hint/TrailingSpaces.hs
  test/Spec.hs
  test/Test/Suggestion.hs
  test/Test/TrailingSpaces.hs
Labels: enhancement, hint

#113 Use custom HLint settings, better logging
  hintman.cabal
  src/Hintman.hs
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Download.hs
  src/Hintman/Effect/TokenStorage.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/HLint.hs
  src/Hintman/Installation.hs
  src/Hintman/Webhook.hs
Labels: enhancement

#126 [#125] Handle 'Removed' lines in diffs
  src/Hintman/Hint/Position.hs
  test/Test/Data.hs
  test/Test/HLint.hs
Labels: diff

#129 [#124] Include TrailingNewlines check
  hintman.cabal
  src/Hintman/Core/Hint.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/TrailingNewlines.hs
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Hint.hs
  test/Test/Hint/HLint.hs
  test/Test/Hint/TrailingNewlines.hs
  test/Test/Hint/TrailingSpaces.hs
Labels: enhancement, hint

#135 [#133] Store `ByteString` instead of `Maybe ByteString` in `ModifedFile`
  src/Hintman/Core/PrInfo.hs
  src/Hintman/Hint.hs
  src/Hintman/Hint/HLint.hs
  src/Hintman/Hint/TrailingNewlines.hs
  src/Hintman/Hint/TrailingSpaces.hs
Labels: refactoring

#134 [#131] Take lengths of previous hunks into account
  src/Hintman/Hint/Position.hs
  test/Test/Data.hs
  test/Test/Hint.hs
  test/Test/Hint/TrailingNewlines.hs
Labels: diff

#143 [#136] Speed up tests by fetching PRs only once
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Hint.hs
  test/Test/Hint/HLint.hs
  test/Test/Hint/TrailingNewlines.hs
  test/Test/Hint/TrailingSpaces.hs
Labels: tests

#145 [#137] Add headers to Trailing* hints
  src/Hintman/Core/Hint.hs
  src/Hintman/Core/Review.hs
  src/Hintman/Hint/HLint.hs
  src/Hintman/Hint/TrailingNewlines.hs
  src/Hintman/Hint/TrailingSpaces.hs
  test/Test/Data.hs
  test/Test/Hint.hs
  test/Test/Hint/HLint.hs
  test/Test/Hint/TrailingNewlines.hs
  test/Test/Hint/TrailingSpaces.hs
Labels: enhancement, hint, refactoring

#144 [#141] Add tests for multiple hints in different hunks
  test/Test/Data.hs
  test/Test/Hint/HLint.hs
Labels: tests

#146 [#102] Style suggestions
  src/Hintman/Hint/HLint.hs
  test/Test/Hint/HLint.hs
Labels: HLint, hint

#147 Extend the README
  README.md
Labels: docs
