Repository kowainik/hintman, pull requests merged in 2019-02, with the labels that each got.

#34 custom monad in servant
  .travis.yml
  hintman.cabal
  src/Hintman.hs
  src/Hintman/Config.hs
  src/Hintman/Server.hs
  src/Hintman/Server/Auth.hs
  stack.yaml
Labels: api

#33 shell script to be used for local/server installation
  hintman-local-install.sh
Labels: script

#42 [#37] Comment signature verification
  hintman.cabal
  src/Hintman/Server/Auth.hs
Labels: api, refactoring

#43 [#38] Refactor HintmanAppM
  hintman.cabal
  src/Hintman.hs
  src/Hintman/App.hs
  src/Hintman/App/Env.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Server.hs
Labels: refactoring

#31 [#21] Add aggregate
  hintman.cabal
  src/Hintman/Config.hs
  src/Hintman/Suggestion/Aggregation.hs
  src/Hintman/Suggestion/Core.hs
  src/Hintman/Suggestion/TrailingNewline.hs
  src/Hintman/Suggestion/TrailingSpaces.hs
  test/Test/Suggestion.hs
Labels: enhancement

#46 [#41] Swap Handler with IO in ReaderT
  src/Hintman/App/Monad.hs
Labels: enhancement

#45 [#44] Use default configuration
  hintman.cabal
  src/Hintman/Config.hs
  test/Spec.hs
  test/Test/Config.hs
Labels: configuration

#47 [#36] Rename Cli Context to Cli Arguments
  src/Hintman.hs
  src/Hintman/App/Monad.hs
  src/Hintman/Cli.hs
  src/Hintman/Suggestion/Core.hs
  src/Hintman/Suggestion/TrailingNewline.hs
  src/Hintman/Suggestion/TrailingSpaces.hs
  test/Test/Suggestion.hs
Labels: refactoring
